name: Update Proxy Subscription

on:
  schedule:
    # Запуск каждые 30 минут
    # (GitHub Free не разрешает запускать чаще чем раз в 5-10 мин, 30 - безопасно)
    - cron: '*/30 * * * *'
  workflow_dispatch: # Кнопка для ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Разрешение на сохранение файлов

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Bot
        run: |
          python bot.py

      - name: Commit and Push
        run: |
          git config --global user.name "ProxyBot"
          git config --global user.email "bot@github.com"
          
          # Добавляем файлы
          git add subscription.txt debug.txt
          
          # Проверяем, изменилось ли что-то, и если да — коммитим
          git diff --quiet && git diff --staged --quiet || (git commit -m "🚀 Update proxies" && git push)
