name: Update Proxy List

on:
  schedule:
    # Запуск каждые 60 минут
    - cron: '0 * * * *'
  workflow_dispatch: # Кнопка для ручного запуска

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: 📦 Install Requirements
        run: |
          pip install -r requirements.txt

      - name: 🚀 Run Bot
        run: |
          python core/bot.py

      - name: 💾 Commit & Push
        run: |
          git config --global user.name "ProxyBot"
          git config --global user.email "bot@github.com"
          git add subscription.txt
          
          # Если есть изменения — коммитим, если нет — не падаем с ошибкой
          git commit -m "🚀 Auto-update $(date -u)" || exit 0
          git push
